predictions_path: results/validation
set_size: 1576 # This must be converted to the size of the validation set
threshold: 0.5
voting_output_path: results/validation/voting.tsv
labels_column:
  - "Self-direction: thought"
  - "Self-direction: action"
  - "Stimulation"
  - "Hedonism"
  - "Achievement"
  - "Power: dominance"
  - "Power: resources"
  - "Face"
  - "Security: personal"
  - "Security: societal"
  - "Tradition"
  - "Conformity: rules"
  - "Conformity: interpersonal"
  - "Humility"
  - "Benevolence: caring"
  - "Benevolence: dependability"
  - "Universalism: concern"
  - "Universalism: nature"
  - "Universalism: tolerance"
  - "Universalism: objectivity"